swagger: '2.0'
info:
  title: product-service
  version: '1'
paths:
  "/products/{productId}":
    get:
      summary: getProductById
      description: ''
      operationId: getProductById.get.products/{productId}
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        required: true
        type: string
      responses:
        '200':
          description: 200 response
  "/products":
    get:
      summary: getAllProducts
      description: ''
      operationId: getAllProducts.get.products
      consumes:
      - application/json
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: 200 response
definitions:
  ProductInterface:
    properties:
      id:
        title: ProductInterface.id
        type: string
      title:
        title: ProductInterface.title
        type: string
      description:
        title: ProductInterface.description
        type: string
      price:
        title: ProductInterface.price
        type: number
      logo:
        title: ProductInterface.logo
        type: string
      count:
        title: ProductInterface.count
        type: number
    required:
    - id
    - title
    - description
    - price
    - logo
    - count
    additionalProperties: false
    title: ProductInterface
    type: object
securityDefinitions: {}