service: import-service
frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::${self:custom.bucketName}"
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::${self:custom.bucketName}/*"
  environment:
    BUCKET: ${self:custom.bucketName}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-auto-swagger

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}
  bucketName: node-vue-aws-cloud-catalogs

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true