swagger: '2.0'
info: 
  title: product-service
  version: '1'

paths: 
  "/import": 
    get: 
      summary: importProductsFile
      description: ''
      operationId: importProductsFile.get.import
      consumes:
      - application/json
      produces:
      - application/json
      parameters: 
        - in: query
          name: name
          type: string
          required: true
      responses: 
        '200':
          description: 200 response
 
